version: '3.7'

services:
  node-s:
    user: root
    restart: always
    build:
      context: .
    ports:
      - "4010-4090:4008"
    networks:
      - custom_network

networks:
  custom_network:
    external: true
