version: '3.7'

services:
    node-sitemap:
        user: root
        restart: always
        build:
            context: .
        ports:
            - '7000-7050:4010'
        networks:
            - custom_network

networks:
    custom_network:
        external: true
